```
<!DOCTYPE html>
<html>
<head>
    <title>เว็บเท่ๆ</title>
    <style>
        body {
            background-color: #333;
            color: #fff;
            font-family: Arial, sans-serif;
            text-align: center;
        }
        
        h1 {
            font-size: 48px;
            margin-bottom: 20px;
        }
        
        p {
            font-size: 24px;
            margin-bottom: 40px;
        }
        
        .button {
            background-color: #4CAF50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        
        .button:hover {
            background-color: #3e8e41;
        }
        
        #ghost {
            display: none;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>
<body>
    <h1>ยินดีต้อนรับสู่เว็บเท่ๆ</h1>
    <p>เว็บนี้ถูกสร้างขึ้นเพื่อแสดงตัวอย่างของเว็บเท่ๆ</p>
    <input type="file" id="fileInput" accept="image/*">
    <button class="button" onclick="showGhost()">
        คลิกที่นี่
    </button>
    <img id="ghost" width="100" height="100">
    
    <script>
        let fileInput = document.getElementById('fileInput');
        let ghost = document.getElementById('ghost');
        
        fileInput.addEventListener('change', function() {
            let file = fileInput.files[0];
            let reader = new FileReader();
            
            reader.onload = function(event) {
                ghost.src = event.target.result;
            };
            
            reader.readAsDataURL(file);
        });
        
        function showGhost() {
            ghost.style.display = "block";
        }
    </script>
</body>
</html>
```
